from datetime import datetime, timezone
from pathlib import Path
import shutil
import subprocess

from setuptools import setup
from setuptools.command.build_py import build_py as _build_py
from setuptools.command.sdist import sdist as _sdist
from distutils.errors import DistutilsExecError


ROOT = Path(__file__).resolve().parent
UI_DIR = ROOT / "ui"
UI_DIST = UI_DIR / "dist"
STATIC_DIR = ROOT / "auditview" / "static"


def _has_static_bundle():
    return (STATIC_DIR / "index.html").is_file()


def _require_static_bundle(reason):
    if _has_static_bundle():
        print(f"Skipping UI build: {reason}; using existing {STATIC_DIR}")
        return
    raise DistutilsExecError(
        f"Cannot build UI: {reason}, and {STATIC_DIR} does not contain a built UI. "
        "Install node and pnpm, then run `pnpm --dir ui build`."
    )


def _build_ui():
    if not UI_DIR.is_dir():
        _require_static_bundle(f"{UI_DIR} is missing")
        return

    missing = [tool for tool in ("node", "pnpm") if shutil.which(tool) is None]
    if missing:
        _require_static_bundle(f"missing required executable(s): {', '.join(missing)}")
        return

    print("Building UI with pnpm")
    subprocess.run(["pnpm", "build"], cwd=UI_DIR, check=True)

    if not (UI_DIST / "index.html").is_file():
        raise DistutilsExecError(f"UI build did not create {UI_DIST / 'index.html'}")

    if STATIC_DIR.exists():
        shutil.rmtree(STATIC_DIR)
    shutil.copytree(UI_DIST, STATIC_DIR)
    print(f"Copied built UI from {UI_DIST} to {STATIC_DIR}")


BUILD_INFO = ROOT / "auditview" / "_build_info.py"


def _git(*args):
    """Stripped stdout of a read-only git command against ROOT, or None."""
    try:
        proc = subprocess.run(("git", "-C", str(ROOT), *args),
                              capture_output=True, text=True)
    except OSError:
        return None
    return proc.stdout.strip() if proc.returncode == 0 else None


def _git_stamp():
    """(commit, dirty, None) for ROOT's checkout, or (None, None, reason)."""
    if shutil.which("git") is None:
        return None, None, "missing required executable: git"

    # `.git` is a *file* in a git worktree, so an isdir() check reports "no repo"
    # for every build made the way the sandbox requires. Ask git instead.
    # The toplevel comparison matters when auditview is vendored inside another
    # repo, or when an unpacked sdist sits under a git-managed $HOME: stamping
    # an unrelated repository's commit is worse than stamping nothing.
    toplevel = _git("rev-parse", "--show-toplevel")
    if toplevel is None:
        return None, None, f"{ROOT} is not inside a git checkout"
    if Path(toplevel).resolve() != ROOT:
        return None, None, f"git toplevel {toplevel} is not {ROOT}"

    commit = _git("rev-parse", "HEAD")
    if not commit:
        return None, None, "git checkout has no HEAD commit"

    # Tracked files only, matching `git describe --dirty`: dist/ and the
    # .claude/worktrees/ copies sit inside the tree and must not flip this.
    status = _git("status", "--porcelain", "--untracked-files=no")
    if status is None:
        return None, None, "git status failed"
    return commit, bool(status), None


def _render_build_info(version, commit, dirty, reason=None):
    header = (
        "# Generated by setup.py at build time; not tracked in git.\n"
        "# Describes the source tree this artifact was built from.\n"
    )
    if reason:
        header += f"# git info unavailable: {reason}\n"
    stamped = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        f"{header}"
        f'VERSION = "{version}"\n'
        f'COMMIT = "{commit}"\n'
        f"DIRTY = {dirty!r}\n"
        f'BUILD_TIME = "{stamped}"\n'
    )


def _write_build_info(text):
    try:
        if BUILD_INFO.is_file() and BUILD_INFO.read_text(encoding="utf-8") == text:
            return True
        BUILD_INFO.write_text(text, encoding="utf-8", newline="\n")
        return True
    except OSError as exc:
        print(f"Warning: could not write {BUILD_INFO}: {exc}")
        return False


def _require_build_info(version, reason):
    """Reuse the stamp the sdist carried, else record an unknown one."""
    if BUILD_INFO.is_file():
        print(f"Skipping build stamp: {reason}; using existing {BUILD_INFO}")
        return
    print(f"Warning: cannot stamp build info: {reason}; recording an unknown commit")
    _write_build_info(_render_build_info(version, "", None, reason))


def _stamp_build_info(version):
    """Write auditview/_build_info.py. Never fails the build.

    `uv build` builds the wheel from the *unpacked sdist*, where there is no
    .git, so the stamp must be produced during sdist and reused there -- the
    same asymmetry _require_static_bundle() handles for the UI bundle. Unlike a
    missing UI, a missing commit stamp does not break the package, so this
    degrades instead of raising; scripts/release.sh is what refuses to ship a
    build whose stamp is unknown, dirty, or not HEAD.
    """
    commit, dirty, reason = _git_stamp()
    if commit is None:
        _require_build_info(version, reason)
        return
    if _write_build_info(_render_build_info(version, commit, dirty)):
        print(f"Stamped {BUILD_INFO}: {commit[:7]}{' (dirty)' if dirty else ''}")
    else:
        _require_build_info(version, f"{BUILD_INFO} is not writable")


class build_py(_build_py):
    def run(self):
        # Both hooks stamp *before* super().run(): build_py globs *.py out of
        # the package directory as it runs, and sdist's egg_info computes the
        # file list, so a file written afterwards reaches neither artifact.
        _stamp_build_info(self.distribution.get_version())
        _build_ui()
        super().run()


class sdist(_sdist):
    def run(self):
        _stamp_build_info(self.distribution.get_version())
        _build_ui()
        super().run()


setup(
    cmdclass={
        "build_py": build_py,
        "sdist": sdist,
    }
)
