"""auditview - line-level code review tool.

Build identity. ``__version__`` comes from installed distribution metadata;
``_build_info`` is generated by ``setup.py`` at build time and is absent from a
source tree that has never been built or installed.
"""
from importlib.metadata import version as _dist_version

try:
    from . import _build_info as _bi
except Exception:  # never built, or a hand-edited stamp that will not parse
    _bi = None

#: Full 40-char commit this build came from; "" when unknown.
__commit__ = getattr(_bi, "COMMIT", "") or ""
#: True/False when the build could read git, None when it could not ask.
__dirty__ = getattr(_bi, "DIRTY", None)
#: UTC ISO-8601 build timestamp; "" when unknown.
__build_time__ = getattr(_bi, "BUILD_TIME", "") or ""

try:
    __version__ = _dist_version("auditview")
except Exception:  # not installed: fall back to the stamp, then to a marker
    __version__ = getattr(_bi, "VERSION", "") or "0.0.0+unknown"


def version_string():
    """Human-readable build identity, e.g. ``0.1.3 (59a7348, dirty)``.

    Falls back to the bare version when the build carries no commit stamp.
    """
    if not __commit__:
        return __version__
    return f"{__version__} ({__commit__[:7]}{', dirty' if __dirty__ else ''})"
